modLoader = "javafml"

loaderVersion = "[36,)"

license = "All rights reserved"

issueTrackerURL = "https://github.com/StylexTV/LYNX/issues"

[[mods]]

modId = "lynx"

version = "1.3.2"

displayName = "LYNX"

displayURL = "https://github.com/StylexTV/LYNX/"

logoFile = "logo.png"

credits = "Thanks to everyone who has contributed on GitHub"

authors = "the LYNX developers (see AUTHORS file)"

description = '''
LYNX is a free and powerful path-finding bot that lets you navigate the vast landscapes of Minecraft without any user intervention.

Additionally, LYNX focuses on efficiency and performance, while also paying attention to reliability and an unobtrusive look. The bot is mainly controlled by chat input and the underlying pathing algorithm is called A*, a perfect algorithm for navigating voxel worlds like Minecraft.

Type '#help' in your in-game chat to get started.
'''

[[dependencies.lynx]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"